### ISSUE TITLE
有的浏览器报上来的stack解析不了

### ISSUE THREAD

**Issue by homkai** [vicwang163/sourcemap-stack#1]
"getIntentPackageLogData@http://xxx.com/xx/xx-asset/xxx/feedCommon.116fce68.js:1:508418
http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:424798
fn@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:414858
http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:424603
Xo@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:434579
d@http://xxx.com/xx/xx-asset/xxx/feedCommon.116fce68.js:1:49955
onNext@http://xxx.com/xx/xx-asset/xxx/feedCommon.116fce68.js:1:743474
http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:178422
submit@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:400894
submit@[native code]
r@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:83961
r@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:22786
executeDispatchesInOrder@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:23622
p@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:19760
forEach@[native code]
exports@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:138034
processEventQueue@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:20796
http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:84288
handleTopLevel@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:84293
i@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:84773
perform@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:135247
batchedUpdates@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:79142
batchedUpdates@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:111839
dispatchEvent@http://xxx.com/xx/xx-asset/xxx/common.a7db9191.js:1:85642
dispatchEvent@[native code]"

**Comment by vicwang163** [comment]
@homkai 你确定报上来是这样的吗，抛开url地址正确，stack是确定这样的吗？有可能检索url地址出错了

**Comment by homkai** [comment]
stack确认是这样的 
userAgent看是 safari
我就是把 我们的域名和项目名 用 xx做了下字符串替换，其他格式 完全没改

**Comment by vicwang163** [comment]
@homkai 已经修复,最新版本0.0.5
